### ISSUE TITLE
_json group does not work

### ISSUE THREAD

**Issue by satoved** [voicecode-bv/laravel-nova-translation-manager#3]
The _json group from .json translation files sends a request, gets a response, but does not render it.

![image](https://user-images.githubusercontent.com/14319239/59157913-d2b36380-8abb-11e9-8439-2c866cdf94a8.png)

**Comment by voicecode-bv** [comment]
@satoved Can you please send me some example sql files I can import? I can't replicate this on my side.

**Comment by satoved** [comment]
Thanks for the quick fixes, the package is really helpful.

Figured it out.

Let's say that the first locale in the settings is 'en'

And /voicecode/nova-translation-manager/locales returns:

```
["en","es","de","ru"]
```

Then it takes the first locale ("en") as a key value here https://github.com/voicecode-bv/laravel-nova-translation-manager/blob/master/resources/js/components/Tool.vue#L61

But if we don't have an english translation for certain key in json file, e.g.:

/voicecode/nova-translation-manager/translations/_json returns:

```
{
   "1X2 Tip":{
      "pt":{
         "id":1867,
         "status":0,
         "locale":"pt",
         "group":"_json",
         "key":"1X2 Tip",
         "value":"Dica 1X2",
      },
      "de":{
         "id":627,
         "status":0,
         "locale":"de",
         "group":"_json",
         "key":"1X2 Tip",
         "value":"Tipp f\u00fcr 3-Weg-Wette",
      }
   }
}
```

It tries to do:

```
translation[locales[0]].key
```

When there is no translation for "en", and as a result it fails getting .key of null.

The solution can be using the key from json response:

![image](https://user-images.githubusercontent.com/14319239/59195051-a2d78f00-8b93-11e9-8922-ff60f30b3bc6.png)

Instead of the key for the first location returned.

**Comment by voicecode-bv** [comment]
@satoved Thanks! I’m working on a fix for this.

**Comment by voicecode-bv** [comment]
@satoved I've got it working using the 0.0.6 release. Can you confirm this?
